<?php
namespace App\Http\Controllers\Api\Admin;
use App\Http\Controllers\Controller; use App\Models\AuditLog; use App\Models\User; use Illuminate\Http\Request; use Illuminate\Support\Facades\Hash; use Spatie\Permission\Models\Permission; use Spatie\Permission\Models\Role;
class AdminController extends Controller {
 public function users(){return response()->json(User::with('roles')->latest()->paginate(50));}
 public function roles(){return response()->json(Role::with('permissions')->orderBy('name')->get());}
 public function permissions(){return response()->json(Permission::orderBy('name')->get());}
 public function createRole(Request $r){$v=$r->validate(['name'=>'required|string|max:100|unique:roles,name','permissions'=>'array','permissions.*'=>'exists:permissions,name']);$role=Role::create(['name'=>$v['name'],'guard_name'=>'web']);$role->syncPermissions($v['permissions']??[]);$this->audit($r,'role.created',$role);return response()->json($role->load('permissions'),201);}
 public function updateRole(Request $r, Role $role){$v=$r->validate(['name'=>'required|string|max:100|unique:roles,name,'.$role->id,'permissions'=>'array','permissions.*'=>'exists:permissions,name']);$role->update(['name'=>$v['name']]);$role->syncPermissions($v['permissions']??[]);$this->audit($r,'role.updated',$role);return response()->json($role->load('permissions'));}
 public function assignRole(Request $r, User $user){$v=$r->validate(['role'=>'nullable|string|exists:roles,name']);if(empty($v['role'])){$user->syncRoles([]);$user->update(['role'=>'unassigned']);$this->audit($r,'user.role_removed',$user);return response()->json($user->load('roles'));}$role=Role::findByName($v['role'],'web');$user->syncRoles([$role]);$user->update(['role'=>$this->legacyRole($role->name)]);$this->audit($r,'user.role_assigned',$user,['role'=>$role->name]);return response()->json($user->load('roles'));}
 public function storeUser(Request $r){$v=$r->validate(['name'=>'required|string|max:255','email'=>'required|email|unique:users,email','matricule'=>'required|string|max:100|unique:users,matricule','password'=>'required|string|min:8','phone'=>'nullable|string|max:50','job_title'=>'nullable|string|max:255','role'=>'nullable|string|exists:roles,name']);$u=User::create(['name'=>$v['name'],'email'=>$v['email'],'matricule'=>$v['matricule'],'password'=>Hash::make($v['password']),'phone'=>$v['phone']??null,'job_title'=>$v['job_title']??null,'role'=>'unassigned','is_active'=>true]); if(!empty($v['role'])){$role=Role::findByName($v['role'],'web');$u->syncRoles([$role]);$u->update(['role'=>$this->legacyRole($role->name)]);} $this->audit($r,'user.created',$u); return response()->json($u->load('roles'),201);}
 public function updateUser(Request $r, User $user){$v=$r->validate(['name'=>'required|string|max:255','email'=>'required|email|unique:users,email,'.$user->id,'matricule'=>'required|string|max:100|unique:users,matricule,'.$user->id,'password'=>'nullable|string|min:8','phone'=>'nullable|string|max:50','job_title'=>'nullable|string|max:255','role'=>'nullable|string|exists:roles,name','is_active'=>'nullable|boolean']);$data=['name'=>$v['name'],'email'=>$v['email'],'matricule'=>$v['matricule'],'phone'=>$v['phone']??null,'job_title'=>$v['job_title']??null];if(!empty($v['password'])){$data['password']=Hash::make($v['password']);}if(array_key_exists('is_active',$v)){$data['is_active']=(bool)$v['is_active'];}$user->update($data);if(array_key_exists('role',$v)){if(empty($v['role'])){$user->syncRoles([]);$user->update(['role'=>'unassigned']);}else{$role=Role::findByName($v['role'],'web');$user->syncRoles([$role]);$user->update(['role'=>$this->legacyRole($role->name)]);}}$this->audit($r,'user.updated',$user);return response()->json($user->load('roles'));}
 public function setActive(Request $r, User $user){$v=$r->validate(['is_active'=>'required|boolean']);$user->update(['is_active'=>$v['is_active']]);$this->audit($r,'user.status_changed',$user,['is_active'=>$v['is_active']]);return response()->json($user);}
 private function legacyRole(string $name):string{$map=['Direction'=>'direction','Coordinateur Projet'=>'coordinateur_projet','Agent Logistique'=>'agent_logistique','Agent Santé'=>'agent_sante','Administrateur'=>'direction']; return $map[$name]??'custom';}
 private function audit(Request $r,string $action,$model,array $new=[]){AuditLog::create(['user_id'=>$r->user()->id,'action'=>$action,'auditable_type'=>$model::class,'auditable_id'=>$model->id,'new_values'=>$new,'ip_address'=>$r->ip(),'user_agent'=>$r->userAgent()]);}
}
