<?php
namespace App\Http\Controllers\Api\Dashboard;
use App\Http\Controllers\Controller;
use App\Mail\PaymentConfirmationMail;
use App\Models\AuditLog;
use App\Models\CommercialDocument;
use App\Models\Payment;
use App\Notifications\PaymentRecordedNotification;
use App\Services\SimplePdfService;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Mail;
class PaymentController extends Controller {
 public function index(Request $r){$q=Payment::with(['document.order','document.source','customer','recorder'])->latest();if($r->status)$q->where('status',$r->status);if($r->search)$q->where(fn($x)=>$x->where('reference','like','%'.$r->search.'%')->orWhereHas('customer',fn($c)=>$c->where('name','like','%'.$r->search.'%')));return response()->json($q->paginate(30));}
 public function store(Request $r, CommercialDocument $document){if($document->type!=='invoice')abort(422,'Un paiement ne peut être associé qu’à une facture.');if(!in_array($document->status,['accepted','partially_paid'],true))abort(422,'La facture doit être acceptée avant d’enregistrer un paiement.');$v=$r->validate(['amount'=>'required|numeric|min:0.01','paid_at'=>'nullable|date','method'=>'required|string|max:50','reference'=>'nullable|string|max:150','notes'=>'nullable|string']);return DB::transaction(function()use($document,$v,$r){$doc=CommercialDocument::lockForUpdate()->findOrFail($document->id);$amount=(float)$v['amount'];$balance=(float)$doc->balance_amount;if($amount>$balance+0.01)abort(422,'Le paiement dépasse le solde restant.');$payment=Payment::create(['commercial_document_id'=>$doc->id,'customer_id'=>$doc->customer_id,'recorded_by'=>$r->user()->id,'amount'=>$amount,'paid_at'=>$v['paid_at']??now(),'method'=>$v['method'],'status'=>'recorded','reference'=>$v['reference']??null,'notes'=>$v['notes']??null]);$this->recalculateDocument($doc);AuditLog::create(['user_id'=>$r->user()->id,'action'=>'payment.created','auditable_type'=>Payment::class,'auditable_id'=>$payment->id,'new_values'=>['amount'=>$amount,'document'=>$doc->document_number,'balance'=>$doc->balance_amount],'ip_address'=>$r->ip(),'user_agent'=>$r->userAgent()]);$doc->load('customer');$r->user()->notify(new PaymentRecordedNotification($payment->load(['document','customer'])));if($doc->customer?->email && config('mail.default')!=='log'){try{Mail::to($doc->customer->email)->send(new PaymentConfirmationMail($payment->load(['document','customer'])));}catch(\Throwable $e){report($e);}}return response()->json($payment->load(['document','customer','recorder']),201);});}
 public function setStatus(Request $r, Payment $payment){$status=$r->validate(['status'=>'required|in:recorded,validated,cancelled'])['status'];if($payment->status==='cancelled' && $status!=='cancelled')abort(422,'Un paiement annulé ne peut pas être réactivé.');if($status==='cancelled' && $payment->status!=='cancelled'){return DB::transaction(function()use($payment,$r){$payment->load('document');$payment->update(['status'=>'cancelled']);$this->recalculateDocument($payment->document);AuditLog::create(['user_id'=>$r->user()->id,'action'=>'payment.cancelled','auditable_type'=>Payment::class,'auditable_id'=>$payment->id,'new_values'=>['document'=>$payment->document->document_number],'ip_address'=>$r->ip(),'user_agent'=>$r->userAgent()]);return response()->json($payment->fresh(['document.order','document.source','customer','recorder']));});}$payment->update(['status'=>$status]);return response()->json($payment->fresh(['document.order','document.source','customer','recorder']));}
 private function recalculateDocument(CommercialDocument $doc):void{$paid=(float)Payment::where('commercial_document_id',$doc->id)->where('status','!=','cancelled')->sum('amount');$balance=max(0,(float)$doc->total_amount-$paid);$status=$balance<=0.01?'closed':($paid>0?'partially_paid':($doc->status==='cancelled'?'cancelled':'accepted'));$doc->update(['paid_amount'=>$paid,'balance_amount'=>$balance,'status'=>$status]);}
 public function pdf(Payment $payment, SimplePdfService $pdf){$payment->load(['document.customer','customer','recorder']);return response($pdf->paymentReceipt($payment),200,['Content-Type'=>'application/pdf','Content-Disposition'=>'inline; filename="PAI-'.$payment->id.'.pdf"','Cache-Control'=>'no-store']);}
 public function email(Request $r, Payment $payment, SimplePdfService $pdf){$to=$r->validate(['email'=>'required|email'])['email'];if(config('mail.default')==='log')abort(422,'SMTP non configuré. Configurez les paramètres MAIL_* dans .env.');$payment->load(['document.customer','customer','recorder']);$bytes=$pdf->paymentReceipt($payment);try{Mail::send('emails.document-available',['title'=>'Reçu de paiement HOPE PAI-'.$payment->id,'document'=>$payment,'recipient'=>$to],function($m)use($to,$bytes,$payment){$m->to($to)->subject('HOPE - Reçu de paiement PAI-'.$payment->id)->attachData($bytes,'PAI-'.$payment->id.'.pdf',['mime'=>'application/pdf']);});\App\Models\DocumentEmailLog::create(['commercial_document_id'=>$payment->commercial_document_id,'recipient'=>$to,'subject'=>'HOPE - Reçu de paiement PAI-'.$payment->id,'status'=>'sent','sent_by'=>$r->user()->id]);return response()->json(['message'=>'Reçu de paiement envoyé à '.$to.'.']);}catch(\Throwable $e){report($e);\App\Models\DocumentEmailLog::create(['commercial_document_id'=>$payment->commercial_document_id,'recipient'=>$to,'subject'=>'HOPE - Reçu de paiement PAI-'.$payment->id,'status'=>'failed','error'=>app()->isLocal()?$e->getMessage():'Erreur SMTP','sent_by'=>$r->user()->id]);return response()->json(['message'=>'Échec de l’envoi email. Vérifiez la configuration SMTP.','error'=>app()->isLocal()?$e->getMessage():null],500);}}
}
