<?php
namespace App\Http\Controllers\Api\Dashboard;
use App\Http\Controllers\Controller;
use App\Models\{PurchaseOrder,InventoryProduct,WarehouseStock,StockMovement};
use App\Services\{DocumentNumberService,SimplePdfService};
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Mail;
class PurchaseOrderController extends Controller {
 private function rules():array{return ['supplier_id'=>'required|exists:suppliers,id','warehouse_id'=>'nullable|exists:warehouses,id','expected_date'=>'nullable|date','discount'=>'nullable|numeric|min:0','currency'=>'nullable|string|size:3','notes'=>'nullable|string','lines'=>'required|array|min:1','lines.*.inventory_product_id'=>'required|exists:inventory_products,id','lines.*.quantity'=>'required|integer|min:1','lines.*.unit_price'=>'nullable|numeric|min:0','lines.*.discount'=>'nullable|numeric|min:0'];}
 public function index(Request $r){$q=PurchaseOrder::with(['supplier','warehouse','lines.product'])->latest();if($r->status)$q->where('status',$r->status);if($r->search)$q->where(fn($x)=>$x->where('order_number','like','%'.$r->search.'%')->orWhereHas('supplier',fn($s)=>$s->where('name','like','%'.$r->search.'%')));return response()->json($q->paginate($r->integer('per_page',25)));}
 public function show(PurchaseOrder $order){return response()->json($order->load(['supplier','warehouse','lines.product']));}
 private function calculate(array $lines,float $discount):array{$sub=0;$rows=[];foreach($lines as $l){$p=InventoryProduct::findOrFail($l['inventory_product_id']);$price=array_key_exists('unit_price',$l)?(float)$l['unit_price']:(float)$p->purchase_price;$lt=max(0,(int)$l['quantity']*$price-(float)($l['discount']??0));$sub+=$lt;$rows[]=[$p,$l,$price,$lt];}return [$sub,max(0,$sub-$discount),$rows];}
 public function store(Request $r,DocumentNumberService $nums){$v=$r->validate($this->rules());return DB::transaction(function()use($v,$r,$nums){[$sub,$total,$rows]=$this->calculate($v['lines'],(float)($v['discount']??0));$o=PurchaseOrder::create(['order_number'=>$nums->next('purchase_order','BCF'),'supplier_id'=>$v['supplier_id'],'warehouse_id'=>$v['warehouse_id']??null,'order_date'=>now()->toDateString(),'expected_date'=>$v['expected_date']??null,'discount'=>$v['discount']??0,'subtotal'=>$sub,'total_amount'=>$total,'currency'=>$v['currency']??'XOF','notes'=>$v['notes']??null,'created_by'=>$r->user()->id]);foreach($rows as [$p,$l,$price,$lt])$o->lines()->create(['inventory_product_id'=>$p->id,'quantity'=>$l['quantity'],'unit_price'=>$price,'discount'=>$l['discount']??0,'line_total'=>$lt]);return response()->json($o->load(['supplier','warehouse','lines.product']),201);});}
 public function update(Request $r,PurchaseOrder $order){abort_unless($order->status==='draft',422,'Seule une commande fournisseur brouillon peut être modifiée.');$v=$r->validate($this->rules());return DB::transaction(function()use($v,$order){[$sub,$total,$rows]=$this->calculate($v['lines'],(float)($v['discount']??0));$order->update(['supplier_id'=>$v['supplier_id'],'warehouse_id'=>$v['warehouse_id']??null,'expected_date'=>$v['expected_date']??null,'discount'=>$v['discount']??0,'subtotal'=>$sub,'total_amount'=>$total,'currency'=>$v['currency']??'XOF','notes'=>$v['notes']??null]);$order->lines()->delete();foreach($rows as [$p,$l,$price,$lt])$order->lines()->create(['inventory_product_id'=>$p->id,'quantity'=>$l['quantity'],'unit_price'=>$price,'discount'=>$l['discount']??0,'line_total'=>$lt]);return response()->json($order->fresh(['supplier','warehouse','lines.product']));});}
 public function validateOrder(PurchaseOrder $order){abort_unless($order->status==='draft',422,'Commande achat déjà validée.');$order->update(['status'=>'validated']);return response()->json($order->fresh());}
 public function receive(Request $r,PurchaseOrder $order){$v=$r->validate(['lines'=>'required|array|min:1','lines.*.inventory_product_id'=>'required|exists:inventory_products,id','lines.*.quantity'=>'required|integer|min:1']);return DB::transaction(function()use($v,$order,$r){abort_unless(in_array($order->status,['validated','partially_received'],true),422,'La commande doit être validée avant réception.');$order->load('lines');foreach($v['lines'] as $x){$line=$order->lines->firstWhere('inventory_product_id',(int)$x['inventory_product_id']);if(!$line)abort(422,'Produit absent de la commande.');$qty=(int)$x['quantity'];$remaining=$line->quantity-$line->received_quantity;if($qty>$remaining)abort(422,'Quantité reçue supérieure au reste.');if($order->warehouse_id){$ws=WarehouseStock::lockForUpdate()->firstOrCreate(['warehouse_id'=>$order->warehouse_id,'inventory_product_id'=>$line->inventory_product_id],['quantity'=>0,'reserved_quantity'=>0]);$beforeWarehouse=(int)$ws->quantity;$ws->increment('quantity',$qty);} $p=InventoryProduct::lockForUpdate()->findOrFail($line->inventory_product_id);$globalBefore=(int)$p->stock_quantity;$p->update(['stock_quantity'=>$globalBefore+$qty]);StockMovement::create(['inventory_product_id'=>$line->inventory_product_id,'warehouse_id'=>$order->warehouse_id,'type'=>'entry','quantity'=>$qty,'stock_before'=>$globalBefore,'stock_after'=>$globalBefore+$qty,'unit_price'=>$line->unit_price,'reference'=>$order->order_number,'reason'=>'Réception commande fournisseur','supplier_id'=>$order->supplier_id,'user_id'=>$r->user()->id]);$line->increment('received_quantity',$qty);}$remaining=$order->lines()->whereColumn('received_quantity','<','quantity')->exists();$order->update(['status'=>$remaining?'partially_received':'received']);return response()->json($order->fresh(['supplier','warehouse','lines.product']));});}
 public function cancel(PurchaseOrder $order){abort_if(in_array($order->status,['received','partially_received'],true),422,'Une commande déjà réceptionnée ne peut pas être annulée.');$order->update(['status'=>'cancelled']);return response()->json($order->fresh());}
 public function pdf(PurchaseOrder $order,SimplePdfService $pdf){return response($pdf->purchaseOrder($order),200,['Content-Type'=>'application/pdf','Content-Disposition'=>'inline; filename="'.$order->order_number.'.pdf"','Cache-Control'=>'no-store']);}
 public function email(Request $request,PurchaseOrder $order,SimplePdfService $pdf){$to=$request->validate(['email'=>'required|email'])['email'];if(config('mail.default')==='log')abort(422,'SMTP non configuré. Configurez les paramètres MAIL_* dans .env.');$bytes=$pdf->purchaseOrder($order);try{Mail::send('emails.document-available',['title'=>'Commande fournisseur HOPE '.$order->order_number,'document'=>$order,'recipient'=>$to],function($m)use($to,$bytes,$order){$m->to($to)->subject('HOPE - Commande fournisseur '.$order->order_number)->attachData($bytes,$order->order_number.'.pdf',['mime'=>'application/pdf']);});\App\Models\DocumentEmailLog::create(['recipient'=>$to,'subject'=>'HOPE - Commande fournisseur '.$order->order_number,'status'=>'sent','sent_by'=>request()->user()->id]);return response()->json(['message'=>'Commande fournisseur envoyée à '.$to.'.']);}catch(\Throwable $e){report($e);\App\Models\DocumentEmailLog::create(['recipient'=>$to,'subject'=>'HOPE - Commande fournisseur '.$order->order_number,'status'=>'failed','error'=>app()->isLocal()?$e->getMessage():'Erreur SMTP','sent_by'=>request()->user()->id]);return response()->json(['message'=>'Échec de l’envoi email. Vérifiez la configuration SMTP.','error'=>app()->isLocal()?$e->getMessage():null],500);}}
}
