<?php
use Illuminate\Database\Migrations\Migration; use Illuminate\Database\Schema\Blueprint; use Illuminate\Support\Facades\Schema;
return new class extends Migration { public function up(): void {
 Schema::create('document_sequences', function(Blueprint $t){$t->id();$t->string('key')->unique();$t->string('prefix');$t->unsignedBigInteger('next_number')->default(1);$t->timestamps();});
 Schema::create('purchase_orders', function(Blueprint $t){$t->id();$t->string('order_number')->unique();$t->foreignId('supplier_id')->constrained()->restrictOnDelete();$t->foreignId('warehouse_id')->nullable()->constrained()->nullOnDelete();$t->enum('status',['draft','validated','partially_received','received','cancelled'])->default('draft');$t->date('order_date');$t->date('expected_date')->nullable();$t->decimal('discount',12,2)->default(0);$t->decimal('subtotal',12,2)->default(0);$t->decimal('total_amount',12,2)->default(0);$t->string('currency',3)->default('XOF');$t->text('notes')->nullable();$t->foreignId('created_by')->nullable()->constrained('users')->nullOnDelete();$t->timestamps();});
 Schema::create('purchase_order_lines', function(Blueprint $t){$t->id();$t->foreignId('purchase_order_id')->constrained()->cascadeOnDelete();$t->foreignId('inventory_product_id')->constrained()->restrictOnDelete();$t->unsignedInteger('quantity');$t->unsignedInteger('received_quantity')->default(0);$t->decimal('unit_price',12,2);$t->decimal('discount',12,2)->default(0);$t->decimal('line_total',12,2);$t->timestamps();});
 Schema::create('delivery_notes', function(Blueprint $t){$t->id();$t->string('delivery_number')->unique();$t->foreignId('sales_order_id')->constrained()->cascadeOnDelete();$t->foreignId('warehouse_id')->nullable()->constrained()->nullOnDelete();$t->enum('status',['draft','delivered','cancelled'])->default('draft');$t->date('delivery_date')->nullable();$t->text('notes')->nullable();$t->foreignId('created_by')->nullable()->constrained('users')->nullOnDelete();$t->timestamps();});
 Schema::create('delivery_note_lines', function(Blueprint $t){$t->id();$t->foreignId('delivery_note_id')->constrained()->cascadeOnDelete();$t->foreignId('inventory_product_id')->constrained()->restrictOnDelete();$t->unsignedInteger('quantity');$t->timestamps();});
 Schema::create('inventory_counts', function(Blueprint $t){$t->id();$t->string('count_number')->unique();$t->foreignId('warehouse_id')->constrained()->restrictOnDelete();$t->enum('status',['draft','validated','cancelled'])->default('draft');$t->date('count_date');$t->text('notes')->nullable();$t->foreignId('created_by')->nullable()->constrained('users')->nullOnDelete();$t->timestamps();});
 Schema::create('inventory_count_lines', function(Blueprint $t){$t->id();$t->foreignId('inventory_count_id')->constrained()->cascadeOnDelete();$t->foreignId('inventory_product_id')->constrained()->restrictOnDelete();$t->unsignedInteger('system_quantity')->default(0);$t->unsignedInteger('counted_quantity')->default(0);$t->integer('difference')->default(0);$t->timestamps();});
 Schema::create('document_email_logs', function(Blueprint $t){$t->id();$t->foreignId('commercial_document_id')->nullable()->constrained()->cascadeOnDelete();$t->foreignId('sales_order_id')->nullable()->constrained()->cascadeOnDelete();$t->string('recipient');$t->string('subject');$t->enum('status',['sent','failed'])->default('sent');$t->text('error')->nullable();$t->foreignId('sent_by')->nullable()->constrained('users')->nullOnDelete();$t->timestamps();});
 } public function down(): void {foreach(['document_email_logs','inventory_count_lines','inventory_counts','delivery_note_lines','delivery_notes','purchase_order_lines','purchase_orders','document_sequences'] as $t) Schema::dropIfExists($t);} };