<?php
namespace App\Http\Controllers\Api\Dashboard;
use App\Http\Controllers\Controller; use App\Models\CommercialDocument; use App\Models\Customer; use App\Models\InventoryProduct; use Illuminate\Http\Request; use Illuminate\Support\Facades\DB; use Illuminate\Support\Str;
class CommercialDocumentController extends Controller {
 private const TYPES=['quote'=>'DEVIS','proforma'=>'FACTURE PROFORMA','invoice'=>'FACTURE DE SOLDE / CLÔTURE','credit_note'=>'FACTURE D\'AVOIR'];
 public function index(Request $r){$q=CommercialDocument::with(['customer','lines.product'])->latest(); if($r->type)$q->where('type',$r->type); if($r->search)$q->where(function($x)use($r){$x->where('document_number','like','%'.$r->search.'%')->orWhereHas('customer',fn($c)=>$c->where('name','like','%'.$r->search.'%'));}); return response()->json($q->paginate($r->integer('per_page',20)));}
 public function show(CommercialDocument $document){return response()->json($document->load(['customer','lines.product','source','creator']));}
 public function store(Request $r){$v=$this->validateDoc($r); return DB::transaction(fn()=>response()->json($this->createDocument($v,$r->user()->id),201));}
 private function validateDoc(Request $r){return $r->validate(['type'=>'required|in:quote,proforma,invoice,credit_note','customer_id'=>'required|exists:customers,id','source_document_id'=>'nullable|exists:commercial_documents,id','issue_date'=>'nullable|date','due_date'=>'nullable|date','valid_until'=>'nullable|date','discount'=>'nullable|numeric|min:0','tax_rate'=>'nullable|numeric|min:0|max:100','currency'=>'nullable|string|size:3','payment_method'=>'nullable|string|max:50','status'=>'nullable|in:draft,sent,accepted,rejected,partially_paid,paid,closed,cancelled','paid_amount'=>'nullable|numeric|min:0','notes'=>'nullable|string','lines'=>'required|array|min:1','lines.*.inventory_product_id'=>'required|exists:inventory_products,id','lines.*.quantity'=>'required|integer|min:1','lines.*.unit_price'=>'nullable|numeric|min:0','lines.*.discount'=>'nullable|numeric|min:0']);}
 private function createDocument($v,$userId){$subtotal=0; foreach($v['lines'] as $line){$p=InventoryProduct::findOrFail($line['inventory_product_id']);$price=array_key_exists('unit_price',$line)?$line['unit_price']:$p->sale_price;$lt=max(0,($line['quantity']*$price)-($line['discount']??0));$subtotal+=$lt;}
 $discount=$v['discount']??0;$taxable=max(0,$subtotal-$discount);$tax=$taxable*(($v['tax_rate']??0)/100);$total=$taxable+$tax;$paid=$v['paid_amount']??0;$type=$v['type'];$status=$v['status']??'draft';
 if($type==='invoice' && $paid>=$total && $total>0)$status='closed'; elseif($type==='invoice' && $paid>0)$status='partially_paid'; if($type==='credit_note')$status=$v['status']??'draft';
 $doc=CommercialDocument::create(['document_number'=>$this->number($type),'type'=>$type,'customer_id'=>$v['customer_id'],'source_document_id'=>$v['source_document_id']??null,'issue_date'=>$v['issue_date']??now()->toDateString(),'due_date'=>$v['due_date']??null,'valid_until'=>$v['valid_until']??null,'discount'=>$discount,'tax_rate'=>$v['tax_rate']??0,'subtotal'=>$subtotal,'tax_amount'=>$tax,'total_amount'=>$total,'paid_amount'=>min($paid,$total),'balance_amount'=>max(0,$total-$paid),'currency'=>$v['currency']??'XOF','payment_method'=>$v['payment_method']??null,'status'=>$status,'notes'=>$v['notes']??null,'created_by'=>$userId]);
 foreach($v['lines'] as $line){$p=InventoryProduct::findOrFail($line['inventory_product_id']);$price=array_key_exists('unit_price',$line)?$line['unit_price']:$p->sale_price;$lt=max(0,($line['quantity']*$price)-($line['discount']??0));$doc->lines()->create(['inventory_product_id'=>$p->id,'quantity'=>$line['quantity'],'unit_price'=>$price,'discount'=>$line['discount']??0,'line_total'=>$lt]);}
 if($type==='invoice' && in_array($status,['partially_paid','closed'],true))$this->applyStock($doc,false); if($type==='credit_note' && $status!=='draft')$this->applyStock($doc,true); return $doc->load(['customer','lines.product']); }
 private function applyStock($doc,$restock){foreach($doc->lines as $line){$p=InventoryProduct::lockForUpdate()->findOrFail($line->inventory_product_id);$before=$p->stock_quantity;$qty=$line->quantity;$after=$restock?$before+$qty:$before-$qty;if($after<0)abort(422,'Stock insuffisant pour '.$p->name);$p->update(['stock_quantity'=>$after]);$p->movements()->create(['type'=>$restock?'entry':'exit','quantity'=>$qty,'stock_before'=>$before,'stock_after'=>$after,'unit_price'=>$line->unit_price,'reference'=>$doc->document_number,'reason'=>$restock?'Avoir / retour client':'Facture de solde','user_id'=>$doc->created_by]);}}
 private function number($type){$prefix=['quote'=>'DEV','proforma'=>'PRO','invoice'=>'FAC','credit_note'=>'AVO'][$type]; return $prefix.'-'.now()->format('Ymd').'-'.Str::upper(Str::random(6));}
 public function convert(Request $r,CommercialDocument $document){$type=$r->validate(['type'=>'required|in:proforma,invoice'])['type']; if($type==='proforma'&&$document->type!=='quote')abort(422,'Seul un devis peut devenir une proforma.'); if($type==='invoice'&&$document->type!=='proforma')abort(422,'Seule une proforma peut devenir une facture de solde.');$document->load('lines');$data=['type'=>$type,'customer_id'=>$document->customer_id,'source_document_id'=>$document->id,'issue_date'=>now()->toDateString(),'currency'=>$document->currency,'lines'=>$document->lines->map(fn($l)=>['inventory_product_id'=>$l->inventory_product_id,'quantity'=>$l->quantity,'unit_price'=>$l->unit_price,'discount'=>$l->discount])->values()->all(),'discount'=>$document->discount,'tax_rate'=>$document->tax_rate,'status'=>'draft','notes'=>'Conversion depuis '.$document->document_number];return DB::transaction(fn()=>response()->json($this->createDocument($data,$r->user()->id),201));}
 public function print(CommercialDocument $document){$document->load(['customer','lines.product','source']); return response()->view('commercial.document',['document'=>$document,'logoUrl'=>url('/images/hope-logo.png'),'types'=>self::TYPES]);}
}
