<?php
namespace App\Http\Controllers\Api\Dashboard;
use App\Http\Controllers\Controller; use App\Models\InventoryProduct; use App\Models\StockMovement; use Illuminate\Http\Request; use Illuminate\Support\Facades\DB;
class InventoryController extends Controller {
 public function index(Request $r){return response()->json(InventoryProduct::withCount('movements')->orderBy('name')->get());}
 public function store(Request $r){$v=$r->validate(['sku'=>'required|string|max:100|unique:inventory_products,sku','name'=>'required|string|max:255','unit'=>'nullable|string|max:30','purchase_price'=>'nullable|numeric|min:0','sale_price'=>'required|numeric|min:0','stock_min'=>'nullable|integer|min:0','currency'=>'nullable|string|size:3','description'=>'nullable|string']); return response()->json(InventoryProduct::create($v),201);}
 public function update(Request $r,InventoryProduct $product){$v=$r->validate(['sku'=>'required|string|max:100|unique:inventory_products,sku,'.$product->id,'name'=>'required|string|max:255','unit'=>'nullable|string|max:30','purchase_price'=>'nullable|numeric|min:0','sale_price'=>'required|numeric|min:0','stock_min'=>'nullable|integer|min:0','currency'=>'nullable|string|size:3','description'=>'nullable|string','is_active'=>'boolean']);$product->update($v);return response()->json($product);}
 public function movement(Request $r,InventoryProduct $product){$v=$r->validate(['type'=>'required|in:entry,exit,adjustment','quantity'=>'required|integer|min:1','unit_price'=>'nullable|numeric|min:0','reference'=>'nullable|string|max:100','reason'=>'nullable|string|max:255','supplier_id'=>'nullable|exists:suppliers,id']); return DB::transaction(function() use($v,$product,$r){$before=$product->stock_quantity; $qty=(int)$v['quantity']; $after=$v['type']==='entry'?$before+$qty:($v['type']==='exit'?$before-$qty:$qty); if($after<0) return response()->json(['message'=>'Stock insuffisant.'],422); $product->update(['stock_quantity'=>$after]); $m=StockMovement::create(array_merge($v,['stock_before'=>$before,'stock_after'=>$after,'user_id'=>$r->user()->id])); return response()->json(['product'=>$product->fresh(),'movement'=>$m],201);});}
 public function movements(Request $r){$q=StockMovement::with(['product','supplier','user'])->latest(); if($r->product_id)$q->where('inventory_product_id',$r->product_id); return response()->json($q->paginate($r->integer('per_page',30)));}
 public function dashboard(){ $products=InventoryProduct::where('is_active',true)->get(); return response()->json(['products_count'=>$products->count(),'stock_units'=>$products->sum('stock_quantity'),'low_stock'=>$products->filter(fn($p)=>$p->stock_quantity <= $p->stock_min)->values(),'inventory_value'=>$products->sum(fn($p)=>$p->stock_quantity*(float)$p->purchase_price)]);}
}
